/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital_managment_project;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JasminBijley
 */
public class Print_Patient extends javax.swing.JFrame {
    
    Connection ct=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Statement st=null;
    int id=0;
    ResultSet rss=null;
    PreparedStatement tps=null;
    PreparedStatement ops=null;
    int ft=0;
        public Print_Patient(int g3) {
        initComponents();
        show_date();
testp();
//DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
String n=null;
String p = null;
int h=0;
int h2=0;

contest();
        try {st=null;
            st = ct.createStatement();
            String s = "SELECT `Pasent_Id`,`Firs_Name`,`Age`,`Gender`,`Maritial`,`Date`,`Address`,`City`,`Phone_Number`,`Doctor_Name`,`Patient_Type`,`Ward_No`,`Bed_No` FROM `pasent_info` WHERE `Pasent_Id`='"+g3+"'";
            rs = st.executeQuery(s);
            while (rs.next()) {
            jLabel20.setText("Patient Name   :"+rs.getString(2));
             jLabel22.setText("Age                   :"+rs.getInt(3));
             jLabel3.setText("Gender             :"+rs.getString(4));
             jLabel12.setText("Maritial Status :"+rs.getString(5));
             jLabel14.setText("Birth Date        :"+rs.getDate(6));
            jLabel16.setText("Address           :"+rs.getString(7));
            jLabel18.setText("City                    :"+rs.getString(8));
            jLabel21.setText("Mobile Number :"+rs.getString(9));
           jLabel23.setText("Doctor Name    :"+rs.getString(10));
           jLabel4.setText("Patient Type     :"+rs.getString(11));
           jLabel13.setText("Ward No            :"+rs.getInt(12));
           jLabel17.setText("Bed No               :"+rs.getInt(13));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Reception.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {st=null;
         DefaultTableModel dt = (DefaultTableModel) jTable2.getModel();
            st = ct.createStatement();
            String s = "SELECT `T_Name`,`T_Fee` FROM `patient_test_info` WHERE `Pasent_Id`='"+g3+"'";
            rs = st.executeQuery(s);
            while (rs.next()) {
        dt.addRow(new Object[]{rs.getString(1),rs.getInt(2)});
            }

        } catch (SQLException ex) {
            Logger.getLogger(Reception.class.getName()).log(Level.SEVERE, null, ex);
        }
 try {st=null;
         DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            st = ct.createStatement();
            String s = "SELECT `O_Name`,`O_Fee` FROM `patient_oparetion_info` WHERE `Pasent_Id`='"+g3+"'";
            rs = st.executeQuery(s);
            while (rs.next()) {
        dt.addRow(new Object[]{rs.getString(1),rs.getInt(2)});
            }

        } catch (SQLException ex) {
            Logger.getLogger(Reception.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    
    public Print_Patient() {
        initComponents();
        show_date();
testp();
      
    }

   
    
    public void testp(){
    Reception r=new Reception();
    //jLabel3.setText("Name"+r.test());
        r.Patient();
    }
      public void contest() {
        try {
            ct = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Print_Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   public void show_date(){
        Date dt=new Date();
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
jLabel5.setText("Date : "+df.format(dt));
//((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(""+df.format(dt));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Gender             :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 230, 310, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Patient Type     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 260, 250, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Management");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 120, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mobile Number : 01862915005");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 80, 310, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("..................................................................................................................................");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 150, 630, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("..................................................................................................................................");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 100, 630, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("........................................");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 660, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Signeture");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 690, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Maritial Status :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 260, 310, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Ward No            :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(340, 290, 250, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Birth Date        :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 290, 310, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Address           :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 320, 310, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("City                    :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(340, 200, 250, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Patient Name   :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 170, 310, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Mobile Number :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(340, 170, 250, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Age                   :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 200, 310, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Doctor Name    :");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(340, 230, 250, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Bed No               :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(340, 320, 250, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Oparetion Name", "Fee"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(330, 360, 290, 230);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Name", "Fee"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(0, 360, 300, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 0, 650, 740);
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 70, 740);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital_managment_project/Close2.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 0, 60, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 60, 70, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(720, 0, 70, 740);

        setSize(new java.awt.Dimension(790, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 PrinterJob job=PrinterJob.getPrinterJob();
   job.setJobName("Print Data");
   job.setPrintable(new Printable() {
       @Override
       public int print(Graphics pg, PageFormat pf, int PageNum){
           //To change body of generated methods, choose Tools | Templates.
      if(PageNum>0){
            return NO_SUCH_PAGE;}
Graphics2D g2=(Graphics2D) pg;
g2.translate(pf.getImageableX(),pf.getImageableX());
 g2.scale(1,0.8);  
   jPanel1.print(g2);
       return Printable.PAGE_EXISTS;
       }
   });
   if(job.printDialog()==true){
   JOptionPane.showMessageDialog(this,"Print success..");
   try{
   job.print();
   }catch(PrinterException P){
   
   }}else{JOptionPane.showMessageDialog(this,"Failed...");}
   
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
